<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\TestJob.Api\TestJob.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\json_payload_1.txt" Link="TestData\json_payload_1.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\json_payload_2.txt" Link="TestData\json_payload_2.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
